spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itheima
    username: root
    password: admin
  application:
    name: user-service
server:
  port: 8081
logging:
  level:
    cn:
      itcast:
        user: debug
eureka:
  client:
    service-url:  # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
      prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
      ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
      lease-expiration-duration-in-seconds: 10 #10s过期
      lease-renewal-interval-in-seconds: 5 #5s续约
      instance-id: ${spring.application.name}:${server.port}